---

# AWS token should be exported beforehand
# export AWS_ACCESS_KEY_ID='AK123'
# export AWS_SECRET_ACCESS_KEY='abc123'

# From http://docs.ansible.com/ansible/guide_aws.html

- name: Provision 5 debian 8.4 t2.small instances @us-west-2
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  tasks:

    - name: Provision managers instances
      ec2:
        group: zscaler-test
        instance_type: t2.small
        image: ami-98e114f8 # see https://wiki.debian.org/Cloud/AmazonEC2Image/Jessie
        wait: true
        exact_count: 2
        region: us-west-2
        key_name: mricher
        count_tag:
           Name: swarm-manager
        instance_tags:
           Name: swarm-manager
      register: ec2

    - name: Add instance public IPs to swarm host group
      add_host: name={{ item.public_ip }} groups=swarm,swarm_manager
      with_items: "{{ ec2.tagged_instances }}"

    - name: Provision nodes instances
      ec2:
        group: zscaler-test
        instance_type: t2.small
        image: ami-98e114f8 # see https://wiki.debian.org/Cloud/AmazonEC2Image/Jessie
        wait: true
        exact_count: 2
        region: us-west-2
        key_name: mricher
        count_tag:
           Name: swarm-node
        instance_tags:
           Name: swarm-node
      register: ec2

    - name: Add instance public IPs to swarm host group
      add_host: name={{ item.public_ip }} groups=swarm,swarm_node
      with_items: "{{ ec2.tagged_instances }}"

  #   - name: Dump inventory
  #   debug:
  #     var: hostvars[inventory_hostname]

- name: Global instances configuration
  hosts: swarm
  remote_user: admin
  gather_facts: false
  become: True
  become_method: sudo

  tasks:
    - name: Wait 30s for DNS resolution
      pause: seconds=30

    - name: Wait for SSH to come up
      wait_for: port=22 delay=30 timeout=180 state=started

    - name: Add docker apt key
      apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

    - name: Add docker repo
      apt_repository: repo='deb https://apt.dockerproject.org/repo debian-jessie main' state=present

    - name: Install docker
      apt: name=docker-engine update_cache=yes

    - name: Install pip
      easy_install: name=pip state=latest

    - name: Install docker wrapper
      apt: name=python-docker update_cache=yes
    
    - name: Install docker python API
      pip: name=docker-py state=latest

- name: Setup discovery backend
  hosts: swarm_manager
  remote_user: admin
  gather_facts: false
  become: True

  tasks:
    - name: Start consul container on managers
      # docker run -d -p 8500:8500 --name=consul progrium/consul -server -bootstrap
      docker_container:
        name: consul
        image: progrium/consul
        ports:
          - "8500:8500"
        state: started
        detach: True
        command: -server -bootstrap

- name: Setup primary cluster manager
  hosts: swarm_manager[0]
  remote_user: admin
  gather_facts: False
  become: True
  become_method: sudo

  tasks:
    - name: Debug
      debug:
        var: groups['swarm_manager'][0]

    - name: Start swarm cluster managers
      # see http://docs.ansible.com/ansible/docker_container_module.html
      docker_container:
        name: swarm
        image: swarm
        exposed:
          - "4000"
        ports:
          - "4000:4000"
        state: started
        detach: True
        command: 
          - "manage"
          - "-H" 
          - ":4000" 
          - "--replication"
          - "--advertise" 
          - "{{ groups['swarm_manager'][0] }}:4000" 
          - "consul://{{ groups['swarm_manager'][0] }}:8500"

- name: Setup secondary cluster manager
  hosts: swarm_manager[1:]
  remote_user: admin
  gather_facts: False
  become: True
  become_method: sudo

  tasks:
    - name: Start swarm cluster managers (replica)
      # docker run -d -p 4000:4000 swarm manage -H :4000 --replication --advertise <manager1_ip>:4000 consul://172.30.0.161:8500
      docker_container:
        name: swarm
        image: swarm
        exposed:
          - "4000"
        ports:
          - "4000:4000"
        state: started
        detach: True
        command: 
          - "manage"
          - "-H" 
          - ":4000" 
          - "--replication"
          - "--advertise" 
          - "{{ inventory_hostname }}:4000" 
          - "consul://{{ groups['swarm_manager'][0] }}:8500"

- name: Setup nodes
  hosts: swarm_node
  remote_user: admin
  gather_facts: False
  become: True
  become_method: sudo

  tasks:
    - name: Check systemd Docker configuration file
      file: state=directory path=/etc/systemd/system/docker.service.d

    - name: Create systemd docker config file socket.conf
      copy:
        content: "[Service]\nExecStart=\nExecStart=/usr/bin/docker daemon -H fd:// -H tcp://0.0.0.0:2375\n"
        dest: /etc/systemd/system/docker.service.d/socket.conf

    - name: Reload systemctl
      command: "systemctl daemon-reload"

    - name: Restart Docker service 
      service: name=docker state=restarted

    - name: Nodes join cluster
      # docker run -d swarm join --advertise=<node_ip>:2375 consul://<consul_ip>:8500
      docker_container:
        name: swarm
        image: swarm
        state: started
        ports:
        detach: True
        command: 
           - "join"
           - "--advertise"
           - "{{ inventory_hostname }}:2375" 
           - "consul://{{ groups['swarm_manager'][0] }}:8500"


