orchestrator:
    engine: "docker"
    endpoint: "tcp://localhost:2376"
    tls-cacert: "./examples/docker-compose/traefik/ca.pem"
    tls-cert: "./examples/docker-compose/traefik/cert.pem"
    tls-key: "./examples/docker-compose/traefik/key.pem"
scalers:
    whoami-compose:
        type: "docker-compose"
        target: "whoami"
        config: "docker-compose.yaml"
    whoami2-compose:
        type: "docker-compose"
        target: "whoami2"
        config: "docker-compose.yaml"
rules:
    whoami-cpu-scale:
        target: "whoami"
        probe: "cmd.execute"
        cmd: "./traefik_rt.sh"
        up: "> 20000"
        down: "< 20000"
        scaler: whoami-compose
        refresh: 3s
    whoami2-cpu-scale:
        target: "whoami2"
        probe: "swarm.cpu_average"
        up: "> 2"
        down: "< 1.5"
        scaler: whoami2-compose
        refresh: 10s
